### ISSUE TITLE
Feature: Support other remote state backends

### ISSUE THREAD

**Issue by lvlcn-t** [caas-team/sparrow#66]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

As of now, our target manager implementation exclusively supports GitLab through its API for registering the sparrow instances. This limitation restricts the versatility and applicability of our tool, especially for users who utilize other Git-based hosting services.

### Proposed Solution

We should refactor the current target manager to leverage either direct Git operations or requesting the GitLab API depending on what the user has configured in his startup config. Additionally this will universally extend our support to any Git-based remote repository.

After implementing this, the configuration options for the target manager will be expanded to include both Git and GitLab, providing users with the flexibility to connect to their preferred Git hosting service. The proposed configuration schema is as follows:

```yaml
targetManager:
  type: git | gitlab
  checkInterval: 1m
  registrationInterval: 1m
  updateInterval: 1m
  unhealthyThreshold: 3m
  git:
    repoUrl: https://my-git-instance.sparrow.com/my-repo.git
    token: gitpat-xxxxxxxxxxxx
  gitlab:
    baseUrl: https://gitlab.com
    token: glpat-xxxxxxxxxxxx
    projectId: 123456
```

### Who Can Address This Issue?

Go devs

### Additional Context

https://github.com/go-git/go-git

**Comment by lvlcn-t** [comment]
I've started to implement this in [refactor/git-target-manager](https://github.com/caas-team/sparrow/tree/refactor/git-target-manager)

### TODO
- [ ] Provide unit tests for `CommitFile` and `DeleteFile` methods
- [ ] Adjust helm chart values with new target manager config

**Comment by lvlcn-t** [comment]
The new config of the target manager after implementing this issue, will look like this:
```yaml
targetManager:
  type: git | gitlab
  checkInterval: 1m
  registrationInterval: 1m
  updateInterval: 1m
  unhealthyThreshold: 3m
  git:
    repoUrl: https://my-git-instance.sparrow.com/my-repo.git
    token: gitpat-xxxxxxxxxxxx
  gitlab:
    baseUrl: https://gitlab.com
    token: glpat-xxxxxxxxxxxx
    projectId: 123456
```

**Comment by lvlcn-t** [comment]
I've split the whole implementation into three branches ([refactor/config-validation](https://github.com/lvlcn-t/sparrow/tree/refactor/config-validation), [refactor/genericize-tarman](https://github.com/lvlcn-t/sparrow/tree/refactor/genericize-tarman), [feat/git-interactor](https://github.com/lvlcn-t/sparrow/tree/feat/git-interactor)) to have smaller pull requests instead of one big ~3k lines changed PR 😅 

To ensure I haven't forgotten anything I'll keep the source branch until all three branches are merged.
