### ISSUE TITLE
Refactoring: Check reconciliation simplification

### ISSUE THREAD

**Issue by puffitos** [caas-team/sparrow#98]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Problem Description

The check (config) reconciliation logic should be simplified. We've currently employed a map of check names to checks, which we are exclusively using to register, delete or update the checks. We're using this map structure, to handle more complicated logic like:

- if the map is empty, register all checks
- iterate over the map and start unregistering checks, in case one of the names is not in the incoming config
- iterate over the created checks (from the incoming config) and update/ register the checks, if they exist in the map.

Even though we are not misusing the data structure, it doesn't make for the most simple experience to have to deal with a map. This makes the whole reconciliation logic (the triplet of functions - `ReconcileCheck`, `registerCheck` and `unregisterCheck`) a tad complicated.

### Solution Description

The sparrow is currently in charge of actively reconciling the configurations of the various checks, when a new runtime.Config appears in its runtime channel.

There are multiple ways we could handle this, but the creation of a dedicated struct which will handle the Checks seems like the way to go. A `ChecksController` if you may, which will handle the reconciliation logic of the Checks (registration, update and removal), depending on the runtime configuration channel. Given the modular approach of the sparrow, this feels like the proper way to go; another component of the struct, which can start, act and shutdown autonomously (like the API, the `TargetManager`, the `Loader` and even the `Check` instances themselves).

A more simple solution would be to just create a simple struct to replace the map[string]Check and add some business logic to it (i.e with `updateConfigForCheck(name string, cfg checks.Config).

The end result should make the registration, update and removal of checks a simple affair, which is easy to read and interpret and, most importantly, test.

### Who can address the issue?

Everyone

**Comment by lvlcn-t** [comment]
I've started with the refactoring in [refactor/check-reconcilation](https://github.com/caas-team/sparrow/tree/refactor/check-reconcilation), I used the [refactor/api](#95) branch as base.

I've extracted the reconciling from the sparrow and implemented a check controller that is used by the reconciler to register and unregister checks.

### TODO
- [ ] Use a Custom Error type in the check controller to address #36 
- [ ] Fix the sparrow and check tests (this will be painful, because most tests need to be completely refactored 💀 )
- [ ] Refactor the openapi specification to use the `check.Name()` method instead of the old map key
- [ ] Consider moving the api handlers completely to the api package. Therefore we can inject the database in the sparrow constructor to the api like already done for the reconciler/check controller
- [ ] Beautify the reconciler and check controller implementation (i.e. move to dedicated files or even a package)
- [ ] Add licensing headers to new files
